### ISSUE TITLE
feature for dummie

### ISSUE THREAD

**Issue by tailorrr** [ConorWilliams/rsinc#1]
Hello

Thanks for the effort so far. Works like a charm. :)

Would it be possible to add a command line argument to send a rclone flag like '--fast-list' ?

Best regards.

**Comment by ConorWilliams** [comment]
Hi thanks for the feature request. I think this should be an easy thing to implement but I'm away at the moment and won't be back till October. I'll add something like this in when I can. Just to be 100% specific: you want to be able to pass arbitrary rclone flags to the calls to which rclone commands? Either the lsjson command or the commands pertaining to moving deleting copying etc?

**Comment by tailorrr** [comment]
Thanks for considering my request.

Regarding your first question, yes exactly. Rsinc should be able to call e.g. the mentioned global flag '-fast-list'. Not sure which other global flags would make sense or not.
And secondly, I think in my case the commands for deleting, moving, coping etc. are meant. Again not sure for other use cases.

**Comment by ConorWilliams** [comment]
This feature has now been implimented, just append any rclone global flags to the end of the rsinc command and they will be passed to the rclone calls.
