### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by darlac** [ConorWilliams/rsinc#11]
I used rsinc before and it worked fine; I changed distro (debian now) and I am facing installations issues - cannot figure what the problem is! 
![image](https://user-images.githubusercontent.com/47395824/75996729-4ad47b80-5ecc-11ea-823c-ee2caa861748.png)
![image](https://user-images.githubusercontent.com/47395824/75996823-6fc8ee80-5ecc-11ea-8385-f1b2e8559d61.png)
any suggestions?
thanks, Dimitris

**Comment by ConorWilliams** [comment]
Looks like the debian version of rclone is  old and does not support the `--files-only` flag. Try instaling the lastest version from their website or compiling it from souce (not too hard they have made it simple).

**Comment by darlac** [comment]
Yep, that was the problem..thanks for the prompt response (and of course for the very helpful code).
