### ISSUE TITLE
needs ujson==1.35

### ISSUE THREAD

**Issue by asch99** [ConorWilliams/rsinc#13]
rsinc only seems to work with ujson==1.35
It appears that more recent versions of ujson do not know how to read/write tuple as a json:
  history, ignores, nest = read(MASTER)
  write(MASTER, [[], [], empty()])
  write(MASTER, (history, ignores, nest))

simple solution:
  make history and ignores part of the master.json dict e.g. {'history': history, 'ignores': ignores}

**Comment by ConorWilliams** [comment]
Thank you for bringing this up, I'll  look into it :+1: 

Your proposed solution looks like an easy fix but I'm in a very busy period at the moment so this is a few weeks away from being patched.
