### ISSUE TITLE
KeyError: 'SHA-1'

### ISSUE THREAD

**Issue by bhuesemann** [ConorWilliams/rsinc#3]
Hi,

after installation and a first successful run I got the following error at the 2nd run:
```
pi@raspberrypi:~ $ rsinc OneDrive

    Copyright 2019 C. J. Williams (CHURCHILL COLLEGE)
    This is free software with ABSOLUTELY NO WARRANTY

Have: "OneDrive", entering sync & merge mode
Crawling: "OneDrive" ⠏Traceback (most recent call last):
  File "/home/pi/.local/bin/rsinc", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.7/site-packages/rsinc/__main__.py", line 308, in main
    rmt = lsl(path_rmt, HASH_NAME, regexs)
  File "/home/pi/.local/lib/python3.7/site-packages/rsinc/rsinc.py", line 222, in lsl
    hashsize += d['Hashes'][hash_name]
KeyError: 'SHA-1'
```
Seems like SHA lib is not available on the pi. Could you please advise what to install or check to fix it?

Thanks,
Bodo

**Comment by bhuesemann** [comment]
I took a look into rsinc.py and executed 
```
pi@raspberrypi:~ $ rclone lsjson --files-only --hash OneDrive
[
{"Path":"Somefile.pptx","Name":"Somefile.pptx","Size":677512,"MimeType":"application/vnd.openxmlformats-officedocument.presentationml.presentation","ModTime":"2019-05-27T15:19:00.000000000+02:00","IsDir":false,"Hashes":{"CRC-32":"69c0339a","DropboxHash":"824f84f65044d85b671cebf9efb803b2e535d808f568bed7428c5d885005f2ef","MD5":"cb961d4b7eb619cc3d4456733ee1aa57","QuickXorHash":"74954f09a01fc863bddb8e37a64fa9934202ced0","SHA-1":"7987cee974266f58fb9068e896ed3fbde725fd8f","Whirlpool":"aef5d7ee900ca04a440b19cd5c2b1946dedfd61a1e8cdf49d583ccb49cbddca2ac9828e73f4736c2e114c6f845c36276418b327370f39e5742308a0f0ae5da74"}}
]
```
The dict of hashes contains SHA-1, so I'm not sure what is the problem here....

**Comment by khurshid-alam** [comment]
Same issue here. Key error

**Comment by ConorWilliams** [comment]
Hi @bhuesemann and @khurshid-alam sorry for the delayed reply on this. Could you please try executing "rclone lsjson --files-only --hash OneDrive:" (or whatever the name of your remote is) and "rclone lsjson --files-only --hash  ~" and confirm that SHA-1 is avaliable in both the local and remote. If its not then you need to change the hash name in ~/.rsinc/config.json to a hash avaliable on both local and remote.

**Comment by ConorWilliams** [comment]
>  File "/home/pi/.local/lib/python3.7/site-packages/rsinc/__main__.py", line 308, in main
>     rmt = lsl(path_rmt, HASH_NAME, regexs)

The key here is it was in the remote that SHA-1 was not avaliable but 

> after installation and a first successful run I got the following error at the 2nd run:

This is still concerning as it should have used the hashing on the first run?

**Comment by bhuesemann** [comment]
> rclone lsjson --files-only --hash OneDrive:

'''
pi@raspberrypi:~/.rsinc $ rclone lsjson --files-only --hash onedrive:
[
{"Path":"Das 3-D Auto.pptx","Name":"Das 3-D Auto.pptx","Size":677512,"MimeType":"application/vnd.openxmlformats-officedocument.presentationml.presentation","ModTime":"2019-05-27T13:19:00Z","IsDir":false,"Hashes":{"QuickXorHash":"74954f09a01fc863bddb8e37a64fa9934202ced0"},"ID":"b!F9bHFMe6_EWIdsu1Az2GrAyTNL6zwkxEvcR3FErciDka59o4o3SGRpMJ9J11UWe0#014IE7XQMBNGQPZEX6XVCK2VGH7NTORDBX"}
]
'''

**Comment by bhuesemann** [comment]
Based on the observation above I've changed the configuration to use QuickXorHash and now it works.
I don't understand why the set of hashes available is diffent when I use OneDrive or onedrive: with rclone.

**Comment by ConorWilliams** [comment]
Ah I understand the issue now. When you type `OneDrive` as there is no `:` rclone hashes the folder on the local machine and therefore uses all the supported hash functions but when you type `onedrive:` rclone "requests" the hashes from the remote server which only provides a subset of the supported hashes :)
