### ISSUE TITLE
cron job fails

### ISSUE THREAD

**Issue by darlac** [ConorWilliams/rsinc#7]
I really like your tool, seems to be working fine and is more efficient than the other rclone implementations. My only problem is that I cannot make it run through cron - I have tried multiple solutions to set the right environmental variables (because I think this is the problem) but I cannot make it work. 
I was wondering if you were successful in using rsinc with cron.

**Comment by ConorWilliams** [comment]
Hi @darlac, I don't have much experiance with cron but I just tested this cron job:
`01 19 * * * /usr/bin/python3 -m rsinc --auto /home/conor/test > /home/conor/last_cron_run.txt` and it worked fine. The `-- auto` is required to bypass the execute check and the pipe to a text file is unecessary (rsinc keeps logs in `~/.rsinc/logs`) but nice for a quick check. Let me know what your cron job looks like / try using mine (appropriatly modified) and let me know what happens.

**Comment by darlac** [comment]
hi @ConorWilliams thank you - this seems to be working fine; not sure why it was not working before (I tried the same configuration w/o the -m flag - and was failing); I will use it for a couple of days and confirm that all is fine.

**Comment by ConorWilliams** [comment]
Has evrything worked as expected @darlac?

**Comment by darlac** [comment]
@ConorWilliams yes, it works as expected! thank you.
