### ISSUE TITLE
initial setup doesn't work with correct password

### ISSUE THREAD

**Issue by NathanBlais** [ConorWilliams/rsinc#8]
I just installed it and I get this error. This is the password I used when I set up rclone originally and works when I use it with rclone itself.

```Copyright 2019 C. J. Williams (CHURCHILL COLLEGE)
This is free software with ABSOLUTELY NO WARRANTY

Starting configuration mode
Path to local root folder i.e "~/": ~/   
Local root is: /root

Path to remote root folder i.e "onedrive:": "el_camino google-drive:"
Remote root is: "el_camino google-drive:"

Finding a matching hash function...
Searching: /root
Enter configuration password:
password:Enter configuration password:
password:
2020/01/12 01:23:02 ERROR : Couldn't decrypt configuration, most likely wrong password.
```

**Comment by ConorWilliams** [comment]
How does rclone handle passwords, does it require the password be inputted with every call to rclone?

**Comment by NathanBlais** [comment]
I don't know how it works, I only downloaded it recently. Would you recommend that I get rid of my password?

**Comment by ConorWilliams** [comment]
I suspect the password is causing the issues try disabling it if possible. Furthermore the name you typed for the remote is two words and I thought rclone remotes had to be a single word/token. if possible it would be great if you could send me the rclone output (and all commands used) that occurs when you copy a file from local to remote using rclone.

**Comment by NathanBlais** [comment]
The token can be two words, a space is considered a legal character. Also, disabling my password fixed the problem

**Comment by ConorWilliams** [comment]
Fantastic I'll look into supporting password in the next version
