### ISSUE TITLE
Initial Configuration failes KeyError: 'Hashes' (Webdav, Hidrive) 

### ISSUE THREAD

**Issue by toammann** [ConorWilliams/rsinc#9]
Hello,
wanted to try out your tool. Unfortunately the initial configuration failes. The rclone remote "hidrive" uses the webdav protocol to connect to the Strato HiDrive cloud. Rclone alone workes fine (listing files/directoryies and so on)

However runnig the initial `rsinc --config` command I get the following error error traceback

```rsinc --config
__________       .__               
\______   \ _____|__| ____   ____  
 |       _//  ___/  |/    \_/ ___\ 
 |    |   \\___ \|  |   |  \  \___ 
 |____|_  /____  >__|___|  /\___  >
        \/     \/        \/     \/ 

Copyright 2019 C. J. Williams (CHURCHILL COLLEGE)
This is free software with ABSOLUTELY NO WARRANTY

Starting configuration mode
Path to local root folder i.e "~/": /home/holzi/HiDrive/test/
Local root is: /home/holzi/HiDrive/test

Path to remote root folder i.e "onedrive:": hidrive:test
Remote root is: hidrive:test

Finding a matching hash function...
Searching: /home/holzi/HiDrive/test
Searching: hidrive:test
Traceback (most recent call last):
  File "/usr/bin/rsinc", line 11, in <module>
    load_entry_point('rsinc==2.13.dev0', 'console_scripts', 'rsinc')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/rsinc/rsinc.py", line 121, in <module>
    config_cli(config_path)
  File "/usr/lib/python3.8/site-packages/rsinc/config.py", line 63, in config_cli
    rmt_hashes = get_hashes(BASE_R)
  File "/usr/lib/python3.8/site-packages/rsinc/config.py", line 36, in get_hashes
    return set(files[0]["Hashes"].keys())
KeyError: 'Hashes'
```
Any suggestions? Many thanks for your help!

**Comment by ConorWilliams** [comment]
Hi toammann thanks for letting me know, something is definitly a miss here. 

Are there any files in hidrive:test? rsinc needs there to be atleast one file in both the remote and local folders during configuration so it can compute there hashes. If this is the case let me know and ill add a better error message.

If thats not the issue it could be your remote does not support file hashes (very unlikely) let me know what the result of this command looks like rclone `lsjson --files-only --hash hidrive:test`

**Comment by toammann** [comment]
Hi,
yes I placed some text files in the "test/" folder. The content of the folder is as follows:
```
[holzi@holzilinux ~]$ rclone lsl hidrive:test
        2 2020-02-09 22:04:00.000000000 Text File
        
[holzi@holzilinux ~]$ ls -l /home/holzi/HiDrive/test/
total 8
-rw-r--r-- 1 holzi holzi 2  9. Feb 22:04 'Text File'
-rw-r--r-- 1 holzi holzi 2  9. Feb 22:04 'Text File (1)'
```
I have no idea if the WebDav resource supports hashes sorry. How do I get this information? 
Here is the output of `rclone lsjson --files-only --hash hidrive:test`:

```[holzi@holzilinux ~]$ rclone lsjson --files-only --hash hidrive:test
[
{"Path":"Text File","Name":"Text File","Size":2,"MimeType":"application/octet-stream","ModTime":"2020-02-09T21:04:00Z","IsDir":false}
]
```

**Comment by ConorWilliams** [comment]
Ahh It looks like hidrive is not reporting hashes to rclone here is what the same command returns on onedrive / dropbox for me:
```

**Comment by ConorWilliams** [comment]
https://rclone.org/webdav/#modified-time-and-hashes

**Comment by toammann** [comment]
oeky, thanks for your time. Syncing the HiDrive cloud on linux is driving me crazy :/
